### ISSUE TITLE
suggest dependency on rgdal

### ISSUE THREAD

**Issue by maelle** [ropensci/slopes#51]
is it still needed?

**Comment by Robinlovelace** [comment]
Probably not, discussed recently with Rosa, thanks for raising this.

**Comment by maelle** [comment]
I noticed because I ran `pak::pak()` when testing things locally, and it failed because rgdal isn't available anymore from CRAN.

**Comment by temospena** [comment]
is it just a matter or removing `rgdal` from the "suggests" (once we already have `sf` at "imports")?

**Comment by Robinlovelace** [comment]
👍

**Comment by maelle** [comment]
thank you!
